### ISSUE TITLE
Could not find artifact blowfish:blowfish:jar:1.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

### ISSUE THREAD

**Issue by gunit84** [dvayanu/burgershop#1]
FYI it's missing dependenicies and not working for me....

[INFO] Building Burgershop Maven Webapp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/blowfish/blowfish/1.0/blowfish-1.0.pom
[WARNING] The POM for blowfish:blowfish:jar:1.0 is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/blowfish/blowfish/1.0/blowfish-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.427s
[INFO] Finished at: Fri Jan 17 08:30:48 EST 2014
[INFO] Final Memory: 5M/10M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project burgershop: Could not resolve dependencies for project de.zaunberg:burgershop:war:1.0-SNAPSHOT: Could not find artifact blowfish:blowfish:jar:1.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[root@tc01 burgershop]#

**Comment by dvayanu** [comment]
Hello gunit84. 
have you tried the following guide: 
http://blog.anotheria.net/msk/the-complete-moskito-integration-guide-step-1/

add this to the pom.xml : 
<pre>
    &lt;repositories&gt;
      &lt;repository&gt;
        &lt;id&gt;anotheria&lt;/id&gt;
        &lt;url&gt;http://nexus.anotheria.net/nexus/content/groups/public &lt;/url&gt;
        &lt;releases&gt;
          &lt;enabled&gt;true&lt;/enabled&gt;
        &lt;/releases&gt;
       &lt;snapshots&gt;
          &lt;enabled&gt;true&lt;/enabled&gt;
        &lt;/snapshots&gt;
      &lt;/repository&gt;
    &lt;/repositories&gt;
<pre>
I hope we can get rid of blowfish in next versions and thus it won't be needed anymore.

Ignore the whitespaces. Apparently making comments in github is not something i am good in.

**Comment by gunit84** [comment]
Thanks for your help Leon, sorry for my ignorance, I am very new to the
java world.

Thanks

**Comment by dvayanu** [comment]
no problem, feel free to ask further.

**Comment by eostermueller** [comment]
I ran into the same problem.
Could you add your repository to the pom.xml here:
https://github.com/dvayanu/burgershop

Thanks,
--Erik

**Comment by dvayanu** [comment]
Hi Eric,

ok will do, but are you aware that there is a better, newer version of the demo here:
https://github.com/anotheria/moskito-demo
subprobject burgershop/burgershop-spring-example ?
It uses/shows new moskito features like tagging, tracers or error catching.

regards
Leon
